# Generated by Django 2.2 on 2019-04-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_dnnreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFileName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predictCsvFile', models.FileField(upload_to='')),
                ('modelFile', models.CharField(choices=[['dnnreg_model_2019-04-20T20H38M11.json', 'dnnreg_model_2019-04-20T20H38M11.json'], ['dnnreg_model_2019-04-20T21H49M40.json', 'dnnreg_model_2019-04-20T21H49M40.json']], default='Machine Learning Model File', max_length=50)),
            ],
        ),
    ]
