# Generated by Django 2.2.5 on 2019-09-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_dnnreg', '0002_modelfilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelfilename',
            name='modelFile',
            field=models.CharField(choices=[['dnnreg_model_2019-04-20T20H38M11.json', 'dnnreg_model_2019-04-20T20H38M11.json'], ['dnnreg_model_2019-04-20T21H49M40.json', 'dnnreg_model_2019-04-20T21H49M40.json'], ['dnnreg_model_2019-04-24T16H35M42.json', 'dnnreg_model_2019-04-24T16H35M42.json'], ['dnnreg_model_2019-04-24T16H41M42.json', 'dnnreg_model_2019-04-24T16H41M42.json']], default='Machine Learning Model File', max_length=50),
        ),
    ]
